version: '3'

services:
  rust-tech-day:
    container_name: rust
    hostname: dev|rust
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "../:/usr/src/myapp"
    tty: true

  rust-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
